spring:
  datasource:
    url: jdbc:h2:file:./mankoff_bank_db
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
  jsons:
    path: src/main/resources/jsons/
    name: _user.json

app:
  currency:
    currentCurrency: USD
    usdToRub: 70
    eurToRub: 75
    rubToRub: 1

